version: 0.0 # CodeDeploy 버전 (프로젝트 버전 x)
os: linux
files:
  - source: / #CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상을 지정(/를 지정하면 전체파일을 이야기한다)
    destination: /home/ec2-user/app/step2/zip/ #source에서 지정한 파일을 받을 위치
    overwrite: yes # 기존 파일들이 있으면 덮어쓸지 결정

permissions: #CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 합니다.
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks: # CodeDeploy 배포 단계에서 실행할 명령어를 지정
  ApplicationStart: # ApplicationStart 단계에서 deploy.sh를 ec2-user 권한으로 실행하게 합니다.
    - location: deploy.sh
  timeout: 60 #60으로 스크립트 실행 60초 이상 수행되면 실패가 되도록한다.(무한정 기다릴 수 없으니 시간 제한을 두어야함)
  runas: ec2-user