version: 0.0 # CodeDeploy 버전 (프로젝트 버전 x)
os: linux
files:
  - source: / #CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상을 지정(/를 지정하면 전체파일을 이야기한다)
    destination: /home/ec2-user/app/step2/zip/ #source에서 지정한 파일을 받을 위치
    overwrite: yes # 기존 파일들이 있으면 덮어쓸지 결정